# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.PositiveSmallIntegerField(choices=[(1, 'Add'), (2, 'Edit'), (3, 'Delete'), (4, 'Access'), (5, 'Cancel'), (6, 'Done'), (7, 'Approve'), (8, 'Comment'), (9, 'Recover')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
