# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.PositiveSmallIntegerField(choices=[(1, 'Add'), (2, 'Edit'), (3, 'Delete'), (4, 'Access'), (5, 'Cancel'), (6, 'Done'), (7, 'Approve'), (8, 'Comment'), (9, 'Recover')], default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('observations', models.CharField(blank=True, max_length=2000)),
                ('object_id', models.PositiveIntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('authorized', models.ManyToManyField(related_name='authorized', to=settings.AUTH_USER_MODEL)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
