# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='related',
            field=models.ManyToManyField(related_name='related', to='history.HistoryRelated'),
        ),
    ]
